services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend-net
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -fs http://localhost:9200/_cluster/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend-net
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.4.2
    user: root
    command: ['filebeat', '-e', '--strict.perms=false']
    volumes:
      - ./observability/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeatdata:/usr/share/filebeat/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.12.0
    ports:
      - '9090:9090'
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheusdata:/prometheus
    networks:
      - backend-net
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:9090/-/ready']
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:13.0.1
    ports:
      - '3001:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafanadata:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - backend-net
    restart: unless-stopped

volumes:
  esdata:
  filebeatdata:
  prometheusdata:
  grafanadata:

networks:
  backend-net:
    external: true
