services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend-net
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -fs http://localhost:9200/_cluster/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend-net
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.4.2
    user: root
    command: ['filebeat', '-e', '--strict.perms=false']
    volumes:
      - ./observability/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeatdata:/usr/share/filebeat/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend-net
    restart: unless-stopped

volumes:
  esdata:
  filebeatdata:

networks:
  backend-net:
    external: true
