services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_subscription_api
    ports:
      - '5438:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    build:
      context: .
      target: migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/github_subscription_api?schema=public
    networks:
      - backend-net

  app:
    build:
      context: .
      target: production
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - path: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/github_subscription_api?schema=public
      NODE_ENV: production
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - backend-net

volumes:
  pgdata:

networks:
  backend-net:
    external: true
