// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: github/v1/github.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "github.v1";

export interface CheckRepositoryExistsRequest {
  owner: string;
  repo: string;
}

export interface CheckRepositoryExistsResponse {
  exists: boolean;
}

export interface GetLatestReleaseRequest {
  owner: string;
  repo: string;
}

export interface GetLatestReleaseResponse {
  id: number;
  repoName: string;
  tagName: string;
  name?: string | undefined;
  htmlUrl: string;
  publishedAt?: string | undefined;
}

function createBaseCheckRepositoryExistsRequest(): CheckRepositoryExistsRequest {
  return { owner: "", repo: "" };
}

export const CheckRepositoryExistsRequest: MessageFns<CheckRepositoryExistsRequest> = {
  encode(message: CheckRepositoryExistsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== "") {
      writer.uint32(10).string(message.owner);
    }
    if (message.repo !== "") {
      writer.uint32(18).string(message.repo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckRepositoryExistsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckRepositoryExistsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.repo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckRepositoryExistsRequest {
    return {
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      repo: isSet(object.repo) ? globalThis.String(object.repo) : "",
    };
  },

  toJSON(message: CheckRepositoryExistsRequest): unknown {
    const obj: any = {};
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.repo !== "") {
      obj.repo = message.repo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckRepositoryExistsRequest>, I>>(base?: I): CheckRepositoryExistsRequest {
    return CheckRepositoryExistsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckRepositoryExistsRequest>, I>>(object: I): CheckRepositoryExistsRequest {
    const message = createBaseCheckRepositoryExistsRequest();
    message.owner = object.owner ?? "";
    message.repo = object.repo ?? "";
    return message;
  },
};

function createBaseCheckRepositoryExistsResponse(): CheckRepositoryExistsResponse {
  return { exists: false };
}

export const CheckRepositoryExistsResponse: MessageFns<CheckRepositoryExistsResponse> = {
  encode(message: CheckRepositoryExistsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.exists !== false) {
      writer.uint32(8).bool(message.exists);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckRepositoryExistsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckRepositoryExistsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.exists = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckRepositoryExistsResponse {
    return { exists: isSet(object.exists) ? globalThis.Boolean(object.exists) : false };
  },

  toJSON(message: CheckRepositoryExistsResponse): unknown {
    const obj: any = {};
    if (message.exists !== false) {
      obj.exists = message.exists;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckRepositoryExistsResponse>, I>>(base?: I): CheckRepositoryExistsResponse {
    return CheckRepositoryExistsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckRepositoryExistsResponse>, I>>(
    object: I,
  ): CheckRepositoryExistsResponse {
    const message = createBaseCheckRepositoryExistsResponse();
    message.exists = object.exists ?? false;
    return message;
  },
};

function createBaseGetLatestReleaseRequest(): GetLatestReleaseRequest {
  return { owner: "", repo: "" };
}

export const GetLatestReleaseRequest: MessageFns<GetLatestReleaseRequest> = {
  encode(message: GetLatestReleaseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== "") {
      writer.uint32(10).string(message.owner);
    }
    if (message.repo !== "") {
      writer.uint32(18).string(message.repo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLatestReleaseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLatestReleaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.repo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLatestReleaseRequest {
    return {
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      repo: isSet(object.repo) ? globalThis.String(object.repo) : "",
    };
  },

  toJSON(message: GetLatestReleaseRequest): unknown {
    const obj: any = {};
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.repo !== "") {
      obj.repo = message.repo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLatestReleaseRequest>, I>>(base?: I): GetLatestReleaseRequest {
    return GetLatestReleaseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLatestReleaseRequest>, I>>(object: I): GetLatestReleaseRequest {
    const message = createBaseGetLatestReleaseRequest();
    message.owner = object.owner ?? "";
    message.repo = object.repo ?? "";
    return message;
  },
};

function createBaseGetLatestReleaseResponse(): GetLatestReleaseResponse {
  return { id: 0, repoName: "", tagName: "", name: undefined, htmlUrl: "", publishedAt: undefined };
}

export const GetLatestReleaseResponse: MessageFns<GetLatestReleaseResponse> = {
  encode(message: GetLatestReleaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.repoName !== "") {
      writer.uint32(18).string(message.repoName);
    }
    if (message.tagName !== "") {
      writer.uint32(26).string(message.tagName);
    }
    if (message.name !== undefined) {
      writer.uint32(34).string(message.name);
    }
    if (message.htmlUrl !== "") {
      writer.uint32(42).string(message.htmlUrl);
    }
    if (message.publishedAt !== undefined) {
      writer.uint32(50).string(message.publishedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLatestReleaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLatestReleaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.repoName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tagName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.htmlUrl = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.publishedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLatestReleaseResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      repoName: isSet(object.repoName)
        ? globalThis.String(object.repoName)
        : isSet(object.repo_name)
        ? globalThis.String(object.repo_name)
        : "",
      tagName: isSet(object.tagName)
        ? globalThis.String(object.tagName)
        : isSet(object.tag_name)
        ? globalThis.String(object.tag_name)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      htmlUrl: isSet(object.htmlUrl)
        ? globalThis.String(object.htmlUrl)
        : isSet(object.html_url)
        ? globalThis.String(object.html_url)
        : "",
      publishedAt: isSet(object.publishedAt)
        ? globalThis.String(object.publishedAt)
        : isSet(object.published_at)
        ? globalThis.String(object.published_at)
        : undefined,
    };
  },

  toJSON(message: GetLatestReleaseResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.repoName !== "") {
      obj.repoName = message.repoName;
    }
    if (message.tagName !== "") {
      obj.tagName = message.tagName;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.htmlUrl !== "") {
      obj.htmlUrl = message.htmlUrl;
    }
    if (message.publishedAt !== undefined) {
      obj.publishedAt = message.publishedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLatestReleaseResponse>, I>>(base?: I): GetLatestReleaseResponse {
    return GetLatestReleaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLatestReleaseResponse>, I>>(object: I): GetLatestReleaseResponse {
    const message = createBaseGetLatestReleaseResponse();
    message.id = object.id ?? 0;
    message.repoName = object.repoName ?? "";
    message.tagName = object.tagName ?? "";
    message.name = object.name ?? undefined;
    message.htmlUrl = object.htmlUrl ?? "";
    message.publishedAt = object.publishedAt ?? undefined;
    return message;
  },
};

export type GithubServiceService = typeof GithubServiceService;
export const GithubServiceService = {
  checkRepositoryExists: {
    path: "/github.v1.GithubService/CheckRepositoryExists" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckRepositoryExistsRequest): Buffer =>
      Buffer.from(CheckRepositoryExistsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckRepositoryExistsRequest => CheckRepositoryExistsRequest.decode(value),
    responseSerialize: (value: CheckRepositoryExistsResponse): Buffer =>
      Buffer.from(CheckRepositoryExistsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckRepositoryExistsResponse => CheckRepositoryExistsResponse.decode(value),
  },
  getLatestRelease: {
    path: "/github.v1.GithubService/GetLatestRelease" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetLatestReleaseRequest): Buffer =>
      Buffer.from(GetLatestReleaseRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetLatestReleaseRequest => GetLatestReleaseRequest.decode(value),
    responseSerialize: (value: GetLatestReleaseResponse): Buffer =>
      Buffer.from(GetLatestReleaseResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetLatestReleaseResponse => GetLatestReleaseResponse.decode(value),
  },
} as const;

export interface GithubServiceServer extends UntypedServiceImplementation {
  checkRepositoryExists: handleUnaryCall<CheckRepositoryExistsRequest, CheckRepositoryExistsResponse>;
  getLatestRelease: handleUnaryCall<GetLatestReleaseRequest, GetLatestReleaseResponse>;
}

export interface GithubServiceClient extends Client {
  checkRepositoryExists(
    request: CheckRepositoryExistsRequest,
    callback: (error: ServiceError | null, response: CheckRepositoryExistsResponse) => void,
  ): ClientUnaryCall;
  checkRepositoryExists(
    request: CheckRepositoryExistsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckRepositoryExistsResponse) => void,
  ): ClientUnaryCall;
  checkRepositoryExists(
    request: CheckRepositoryExistsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckRepositoryExistsResponse) => void,
  ): ClientUnaryCall;
  getLatestRelease(
    request: GetLatestReleaseRequest,
    callback: (error: ServiceError | null, response: GetLatestReleaseResponse) => void,
  ): ClientUnaryCall;
  getLatestRelease(
    request: GetLatestReleaseRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetLatestReleaseResponse) => void,
  ): ClientUnaryCall;
  getLatestRelease(
    request: GetLatestReleaseRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetLatestReleaseResponse) => void,
  ): ClientUnaryCall;
}

export const GithubServiceClient = makeGenericClientConstructor(
  GithubServiceService,
  "github.v1.GithubService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): GithubServiceClient;
  service: typeof GithubServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
