name: Continuous Integration Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['feature/hw3-solid-grasp']

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma client
        run: npm run generate:prisma

      - name: Check code formatting
        run: npm run format:diff

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build project
        run: npm run build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: quality

    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma client
        run: npm run generate:prisma

      - name: Run unit tests
        run: npm run test:unit

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run integration tests in Docker
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-int test-int

      - name: Cleanup Docker test infrastructure
        if: always()
        run: docker compose -f docker-compose.test.yml down -v

  e2e-tests:
    name: End-to-end Tests
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run e2e tests in Docker
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-e2e test-e2e

      - name: Cleanup Docker test infrastructure
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
